spring.application.name=match-service
server.port=${MATCH_SERVICE_PORT:8082}

riot.api.key=${RIOT_API_KEY}
riot.api.platform-url-template=${RIOT_PLATFORM_URL_TEMPLATE:https://{region}.api.riotgames.com}
player.service.url=${PLAYER_SERVICE_URL:http://localhost:8081}
